name: parkingson
description: "Parking reminder app - never forget to pay for parking"
publish_to: 'none'

version: 0.1.0+9

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.5
  geolocator: ^13.0.2
  geocoding: ^4.0.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  google_mobile_ads: ^9.0.0
  in_app_purchase: ^3.2.0
  flutter_background_service: ^5.0.7
  url_launcher: ^6.3.1
  intl: ^0.20.2
  flutter_tts: ^4.2.0
  android_intent_plus: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
